# Generated by Django 5.1.1 on 2024-10-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=100)),
                ('has_jwt', models.BooleanField()),
                ('request_date', models.DateTimeField()),
                ('request_method', models.CharField(max_length=100)),
                ('request_total_time', models.FloatField()),
            ],
        ),
    ]
