# Generated by Django 5.1.1 on 2024-10-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_total_time',
            field=models.DurationField(),
        ),
    ]
